//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ваучер
    {
        public int Код_ваучера { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public string ФИО_клиента { get; set; }
        public string Ваучер_на_трансфер { get; set; }
        public string Ваучер_на_заселение { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
