//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документы
    {
        public int Код_документов { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public string Билет_на_самолет { get; set; }
        public string Страховой_полис { get; set; }
        public string Виза { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
