//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int Код_заявки { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public string Предпочтения { get; set; }
        public string Тип_питания { get; set; }
        public Nullable<System.DateTime> Дата_тура { get; set; }
        public Nullable<int> Код_тура { get; set; }
        public Nullable<int> Верхняя_грань_стоимости { get; set; }
        public Nullable<int> Нижняя_грань_стоимости { get; set; }
        public string Дополнительные_услуги { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Тип_питания Тип_питания1 { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
