//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Туры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Туры()
        {
            this.Тип_Тур = new HashSet<Тип_Тур>();
            this.Тур_Отель = new HashSet<Тур_Отель>();
        }
    
        public int Код_тура { get; set; }
        public string Название { get; set; }
        public Nullable<int> Перечень_услуг { get; set; }
        public string Код_страны { get; set; }
        public Nullable<int> Количество_билетов { get; set; }
        public Nullable<int> Стоимость { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тип_Тур> Тип_Тур { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тур_Отель> Тур_Отель { get; set; }
    }
}
