//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тур_Отель
    {
        public int Код_отельтур { get; set; }
        public Nullable<int> Код_отеля { get; set; }
        public Nullable<int> Код_тура { get; set; }
    
        public virtual Отели Отели { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
